import type { Course, Lesson } from "@/lib/types"

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Introduction to Cryptocurrency Trading",
    description:
      "Learn the fundamentals of crypto trading, from understanding blockchain to placing your first trade.",
    thumbnailUrl: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&h=450&fit=crop",
    instructorId: "inst-1",
    instructorName: "Sarah Chen",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&fit=crop&crop=face",
    level: "beginner",
    pricing: "free",
    price: null,
    currency: "USD",
    status: "published",
    totalLessons: 12,
    totalDuration: 180,
    enrolledCount: 1240,
    rating: 4.8,
    createdAt: "2025-11-01T00:00:00Z",
    updatedAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "2",
    title: "Technical Analysis Masterclass",
    description:
      "Master chart patterns, indicators, and price action strategies used by professional traders.",
    thumbnailUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=450&fit=crop",
    instructorId: "inst-2",
    instructorName: "Marcus Johnson",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96&h=96&fit=crop&crop=face",
    level: "intermediate",
    pricing: "paid",
    price: 49.99,
    currency: "USD",
    status: "published",
    totalLessons: 24,
    totalDuration: 480,
    enrolledCount: 856,
    rating: 4.6,
    createdAt: "2025-10-15T00:00:00Z",
    updatedAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "3",
    title: "DeFi Fundamentals",
    description:
      "Understand decentralized finance protocols, yield farming, and liquidity provision.",
    thumbnailUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=450&fit=crop",
    instructorId: "inst-1",
    instructorName: "Sarah Chen",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&fit=crop&crop=face",
    level: "intermediate",
    pricing: "paid",
    price: 39.99,
    currency: "USD",
    status: "published",
    totalLessons: 16,
    totalDuration: 320,
    enrolledCount: 623,
    rating: 4.7,
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "4",
    title: "Risk Management for Traders",
    description:
      "Learn position sizing, stop-loss strategies, and portfolio management techniques.",
    thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop",
    instructorId: "inst-3",
    instructorName: "David Park",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=96&h=96&fit=crop&crop=face",
    level: "advanced",
    pricing: "paid",
    price: 59.99,
    currency: "USD",
    status: "published",
    totalLessons: 18,
    totalDuration: 360,
    enrolledCount: 412,
    rating: 4.9,
    createdAt: "2025-09-20T00:00:00Z",
    updatedAt: "2025-12-30T00:00:00Z",
  },
  {
    id: "5",
    title: "Blockchain Development Basics",
    description:
      "Get started with smart contracts, Solidity, and building on Ethereum.",
    thumbnailUrl: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=800&h=450&fit=crop",
    instructorId: "inst-4",
    instructorName: "Elena Rodriguez",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=96&h=96&fit=crop&crop=face",
    level: "beginner",
    pricing: "free",
    price: null,
    currency: "USD",
    status: "published",
    totalLessons: 10,
    totalDuration: 150,
    enrolledCount: 2100,
    rating: 4.5,
    createdAt: "2025-08-10T00:00:00Z",
    updatedAt: "2025-11-25T00:00:00Z",
  },
  {
    id: "6",
    title: "Futures Trading Strategies",
    description:
      "Advanced perpetual futures trading with leverage management and liquidation prevention.",
    thumbnailUrl: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&h=450&fit=crop",
    instructorId: "inst-2",
    instructorName: "Marcus Johnson",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96&h=96&fit=crop&crop=face",
    level: "advanced",
    pricing: "paid",
    price: 79.99,
    currency: "USD",
    status: "published",
    totalLessons: 20,
    totalDuration: 400,
    enrolledCount: 318,
    rating: 4.7,
    createdAt: "2026-01-05T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "7",
    title: "NFT Trading & Investing",
    description:
      "Navigate the NFT marketplace — from evaluating collections to flipping strategies.",
    thumbnailUrl: "",
    instructorId: "inst-1",
    instructorName: "Sarah Chen",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&fit=crop&crop=face",
    level: "beginner",
    pricing: "paid",
    price: 29.99,
    currency: "USD",
    status: "draft",
    totalLessons: 4,
    totalDuration: 60,
    enrolledCount: 0,
    rating: null,
    createdAt: "2026-01-28T00:00:00Z",
    updatedAt: "2026-02-05T00:00:00Z",
  },
  {
    id: "8",
    title: "Algo Trading with Python",
    description:
      "Build automated trading bots using Python, pandas, and exchange APIs.",
    thumbnailUrl: "",
    instructorId: "inst-1",
    instructorName: "Sarah Chen",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&fit=crop&crop=face",
    level: "advanced",
    pricing: "paid",
    price: 69.99,
    currency: "USD",
    status: "draft",
    totalLessons: 0,
    totalDuration: 0,
    enrolledCount: 0,
    rating: null,
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-02-06T00:00:00Z",
  },
  {
    id: "9",
    title: "Crypto Tax & Compliance Guide",
    description:
      "Understand tax obligations, reporting requirements, and compliance for crypto traders.",
    thumbnailUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop",
    instructorId: "inst-1",
    instructorName: "Sarah Chen",
    instructorAvatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&fit=crop&crop=face",
    level: "intermediate",
    pricing: "paid",
    price: 34.99,
    currency: "USD",
    status: "archived",
    totalLessons: 8,
    totalDuration: 120,
    enrolledCount: 195,
    rating: 4.2,
    createdAt: "2025-06-15T00:00:00Z",
    updatedAt: "2025-10-01T00:00:00Z",
  },
]

// Public domain / CC0 video samples for lesson playback
export const mockLessons: Lesson[] = [
  {
    id: "l-1",
    courseId: "1",
    title: "What is Cryptocurrency?",
    description: "An overview of digital currencies and blockchain technology.",
    type: "video" as const,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    content: null,
    duration: 15,
    order: 1,
    isFree: true,
  },
  {
    id: "l-2",
    courseId: "1",
    title: "Understanding Blockchain",
    description: "How blockchain works under the hood — blocks, hashes, and consensus.",
    type: "video" as const,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    content: null,
    duration: 10,
    order: 2,
    isFree: true,
  },
  {
    id: "l-3",
    courseId: "1",
    title: "Setting Up Your First Wallet",
    description: "Step-by-step guide to creating a crypto wallet.",
    type: "video" as const,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    content: null,
    duration: 20,
    order: 3,
    isFree: false,
  },
  {
    id: "l-4",
    courseId: "1",
    title: "Your First Trade",
    description: "Placing buy and sell orders on an exchange.",
    type: "video" as const,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    content: null,
    duration: 25,
    order: 4,
    isFree: false,
  },
  {
    id: "l-5",
    courseId: "1",
    title: "Reading Candlestick Charts",
    description: "Understanding OHLC data and candlestick patterns for beginners.",
    type: "video" as const,
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    content: null,
    duration: 18,
    order: 5,
    isFree: false,
  },
  {
    id: "l-6",
    courseId: "1",
    title: "Live Q&A Session",
    description: "Ask the instructor anything about crypto trading.",
    type: "live" as const,
    videoUrl: null,
    content: null,
    duration: 60,
    order: 6,
    isFree: false,
  },
]
